version: '3.9'

services:
  api:
    ports:
      # Exposes application port.
      - "8000:8000"
    volumes:
      # Adds current directory as volume.
      - .:/app/src/
    environment:
      # Enables autoreload.
      QUANTEX_RELOAD: "True"

  pgadmin:
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-root}
    ports:
      - "5050:80"
    networks:
      - quantex_default  # Add this line to connect to the existing network

networks:
  quantex_default: # Add this section to define the existing network
    external:
      name: quantex_default
